import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "foundation-sites/dist/css/foundation.min.css";
import FoundationInit from "./FoundationInit";
import Header from "@/components/Header";
import { LocaleProvider } from "@/context/LocaleContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LocaleProvider>
          <Header />
          <main className="grid-container">
            {children}
          </main>
          <FoundationInit />
        </LocaleProvider>
      </body>
    </html>
  );
}
