import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'foundation-sites/dist/css/foundation.min.css';
import FoundationInit from './FoundationInit';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { LocaleProvider } from '@/context/LocaleContext';
import { AuthProvider } from '@/context/AuthContext';
import { GoogleOAuthProvider } from '@react-oauth/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Truek',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LocaleProvider>
          <AuthProvider>
            <GoogleOAuthProvider
              clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
            >
              <Header />
              <main style={{ minHeight: '100vh', width: '100%' }}>
                {children}
              </main>
              <Footer />
              <FoundationInit />
            </GoogleOAuthProvider>
          </AuthProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
